// Date: 11/16/2015 11:44:22 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelMannCoSupplyCrate extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
  
  public ModelMannCoSupplyCrate()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1.mirror = true;
      Shape1 = new ModelRenderer(this, 0, 12);
      Shape1.addBox(0F, 0F, 0F, 8, 1, 8);
      Shape1.setRotationPoint(-4F, 23F, -4F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1.mirror = false;
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(0F, 0F, 0F, 6, 6, 6);
      Shape2.setRotationPoint(-3F, 17F, -3F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 12);
      Shape3.addBox(0F, 0F, 0F, 8, 1, 8);
      Shape3.setRotationPoint(-4F, 16F, -4F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 8, 21);
      Shape4.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape4.setRotationPoint(3F, 17F, 3F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 4, 21);
      Shape5.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape5.setRotationPoint(3F, 17F, -4F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 12, 21);
      Shape6.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape6.setRotationPoint(-4F, 17F, 3F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 21);
      Shape7.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape7.setRotationPoint(-4F, 17F, -4F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 0, 28);
      Shape8.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape8.setRotationPoint(-5F, 20F, -5F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, -0.2617994F);
      Shape9 = new ModelRenderer(this, 0, 28);
      Shape9.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape9.setRotationPoint(-5F, 22.5F, 5F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 1.570796F, -0.2617994F);
      Shape10 = new ModelRenderer(this, 0, 28);
      Shape10.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape10.setRotationPoint(-5F, 22.5F, 4F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, -0.2617994F);
      Shape11 = new ModelRenderer(this, 0, 28);
      Shape11.addBox(0F, 0F, 0F, 10, 1, 1);
      Shape11.setRotationPoint(4F, 20F, 5F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 1.570796F, -0.2617994F);
      Shape12 = new ModelRenderer(this, 24, 0);
      Shape12.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape12.setRotationPoint(-1F, 15F, -5F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 24, 0);
      Shape13.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape13.setRotationPoint(0F, 15F, 4F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 42, 0);
      Shape14.addBox(0F, 0F, 0F, 1, 1, 10);
      Shape14.setRotationPoint(-1F, 15F, -5F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0.1745329F, 0F);
      Shape15 = new ModelRenderer(this, 28, -3);
      Shape15.addBox(0F, 0F, 0F, 0, 6, 3);
      Shape15.setRotationPoint(1F, 18F, -6F);
      Shape15.setTextureSize(64, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0.267686F, -0.7435722F, 0.4461433F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape12.render(f5);
    Shape13.render(f5);
    Shape14.render(f5);
    Shape15.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
